#include <cstdio>
#include <fstream>
#include <string>
#include <iostream>
#include <list>
using namespace std;

/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610 ...
3 6 9 12

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

int getFEvenSumm(int lim){
	int x1 = 1, x2 = 1, x3 = 0, i = 3, sum = 0;
	while(true){
		x3 = x1 + x2;
		x1 = x2, x2 = x3;
		if(x3 >= lim)
			break;
		if(i % 3 == 0)
			sum += x3;
		i++;
	}
	return sum;
}

int getFibonacci(int N){
	if(N == 1)
		return 1;
	if(N == 2)
		return 2;
	int x1 = 1, x2 = 2, x3 = 0;
	for(int i = 0; i < N-2; i++){
		x3 = x1 + x2;
		x1 = x2, x2 = x3;
	}
	return x3;
}

void fibGenerator(){
	int fibNum = 0;
	while(true){
		cout << "\nEnter number: ";
		cin >> fibNum;
		if(fibNum <= 0)
			return;
		cout << "\nFibbonaci:\t" << getFibonacci(fibNum) << "\n";
	}
}

void fibEvSummer(){
	int lim = 0;
	while(true){
	cout << "Sum of even Fibonacci numbers below ";
	cin >> lim;
	if(lim <= 0){
		cout << "\nExiting...";
		return;
	}
	cout << "is " << getFEvenSumm(lim) << "\n\n";
	}
}

int main(){
	fibEvSummer();
}